---
# tasks file for encryption

- name: create encryption key
  shell: head -c 32 /dev/urandom | base64
  register: encryption_key

- name: create encryption config file
  template:
     src: encryption-config.yaml.j2
     dest: /var/lib/kubernetes/encryption-config.yaml 
