---

all:
  hosts:
    localhost:
  children:
    k8-lb:
      hosts:
        k8-lb
    k8-master:
      hosts:
        k8-master-hard:
    k8-node:
      hosts:
        k8-node-hard:
    etcd:
      hosts:
        k8-master-hard:
