---
# tasks file for k8-LB

- name: install haproxy
  yum:
     name: haproxy
     state: present
  notify:
     - add hosts in hosts file
     - fix haproxy bind issue


- name: copy configuration file to haproxy
  template:
     src: haproxy.cfg.j2
     dest: /etc/haproxy/haproxy.cfg
  notify: 
     - enable and start haproxy


